#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLRequestSerialization.h>

/**
* Demo Client for Passmeister Apple Wallet and Google Wallet API
* [www.passmeister.com](https://www.passmeister.com).
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface SWGJSONRequestSerializer : AFJSONRequestSerializer
@end
